
// Шкала скруглений (borderRadius): 4 / 8 / 12 / 16 / 20.
//   4  — прогресс-бары, тонкие индикаторы
//   8  — мелкие контролы: инпуты, иконки-кнопки, чипы, пункты меню
//   12 — кнопки, поля, тулбары, тоглы
//   16 — карточки списков, таблицы
//   20 — крупные блоки: шапка-герой, модалы, карточки разделов
// Шкала отступов (padding/margin/gap, ориентир): 4 / 8 / 12 / 16 / 24.
export const makeStyles = (C) => ({
  app: { minHeight: "100vh", background: C.pageGrad, backgroundAttachment: "fixed", color: C.text, fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Inter', system-ui, sans-serif", WebkitFontSmoothing: "antialiased", letterSpacing: "-0.01em" },
  topbar: { height: 60, display: "flex", alignItems: "center", gap: 14, padding: "0 16px", borderBottom: `1px solid ${C.glassBorder}`, position: "sticky", top: 0, zIndex: 40 },
  burger: { width: 40, height: 40, borderRadius: "50%", color: C.text, cursor: "pointer", display: "grid", placeItems: "center", flexShrink: 0 },
  brand: { display: "flex", alignItems: "center", gap: 11 },
  logo: { width: 36, height: 36, borderRadius: 11, background: C.green, color: C.onAccent, display: "grid", placeItems: "center", boxShadow: `0 4px 14px ${C.green}40` },
  brandTxt: { fontSize: 18, fontWeight: 800, letterSpacing: -0.4 }, brandThin: { color: C.sub, fontWeight: 500 },
  searchWrap: { flex: 1, maxWidth: 420, display: "flex", alignItems: "center", gap: 9, background: C.panel, border: `1px solid ${C.line}`, borderRadius: 12, padding: "0 14px", height: 40 },
  search: { flex: 1, background: "transparent", border: "none", outline: "none", color: C.text, fontSize: 13, fontFamily: "inherit" },
  topRight: { display: "flex", alignItems: "center", gap: 14, marginLeft: "auto" },
  user: { textAlign: "right" }, uName: { fontSize: 13, fontWeight: 700 }, uRole: { fontSize: 11, color: C.sub },
  iconBtn: { width: 40, height: 40, borderRadius: "50%", background: C.panel2, border: `1px solid ${C.glassBorder}`, color: C.sub, cursor: "pointer", display: "grid", placeItems: "center", boxShadow: `inset 0 1px 0 ${C.glassHi}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  avatar: { width: 40, height: 40, borderRadius: "50%", background: C.green, color: C.onAccent, display: "grid", placeItems: "center", fontWeight: 800, fontSize: 13, cursor: "pointer", userSelect: "none", boxShadow: `inset 0 1px 0 rgba(255,255,255,0.35)` },
  profileWrap: { position: "relative" },
  profileOverlay: { position: "fixed", inset: 0, zIndex: 60, background: "rgba(0,0,0,0.4)", backdropFilter: "blur(6px)", WebkitBackdropFilter: "blur(6px)" },
  profileMenu: { position: "absolute", top: 48, right: 0, width: 240, background: C.solid, backdropFilter: "blur(28px) saturate(180%)", WebkitBackdropFilter: "blur(28px) saturate(180%)", border: `1px solid ${C.glassBorder}`, borderRadius: 16, padding: 8, zIndex: 61, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 16px 40px ${C.shadow}` },
  pmHead: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, padding: "8px 10px 12px", borderBottom: `1px solid ${C.line}`, marginBottom: 6 },
  pmName: { fontSize: 14, fontWeight: 700 },
  pmMail: { fontSize: 12, color: C.sub, marginTop: 2 },
  pmLang: { width: 42, height: 42, borderRadius: "50%", background: C.panel2, border: `1px solid ${C.line}`, color: C.text, cursor: "pointer", display: "grid", placeItems: "center", fontWeight: 700, fontSize: 13, userSelect: "none", flexShrink: 0 },
  pmItem: { display: "flex", alignItems: "center", gap: 11, padding: "10px 10px", borderRadius: 8, fontSize: 13.5, color: C.text, cursor: "pointer", fontWeight: 500 },
  pmDivider: { height: 1, background: C.line, margin: "6px 4px" },
  themeToggle: { display: "flex", gap: 4, background: C.panel2, borderRadius: 12, padding: 4, margin: "4px 2px 8px" },
  themeBtn: { flex: 1, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 6, padding: "8px", borderRadius: 8, background: "transparent", border: "none", color: C.sub, fontSize: 12.5, cursor: "pointer", fontFamily: "inherit", fontWeight: 600 },
  themeBtnOn: { background: C.panel, color: C.text, boxShadow: `0 1px 4px ${C.shadow}` },
  // Лента вкладок раздела как свитчер: стеклянный трек-капсула на всю ширину,
  // со скользящей пилюлей (modPill) под активной вкладкой; не влезшие вкладки —
  // горизонтальным скроллом внутри трека (скроллбар скрыт классом .modbar).
  // Стекло трека/пилюли — в css.js (.modbar/.modpill), здесь только раскладка.
  modBar: { position: "sticky", top: 60, zIndex: 30, display: "flex", alignItems: "center", gap: 4, height: 60, boxSizing: "border-box", margin: "8px 8px 0", padding: "0 6px", borderRadius: 99, overflowX: "auto", overflowY: "hidden" },
  mod: { position: "relative", zIndex: 1, flexShrink: 0, display: "flex", alignItems: "center", gap: 8, padding: "0 16px", height: "100%", fontSize: 13, fontWeight: 600, color: C.sub, cursor: "pointer", whiteSpace: "nowrap", transition: "color .2s" },
  modActive: { color: C.text },
  // Скользящая стеклянная пилюля под активной вкладкой (left/width/opacity — из замера в AppShell)
  modPill: { position: "absolute", top: 6, height: "calc(100% - 12px)", borderRadius: 99, transition: "left .35s cubic-bezier(.34,1.1,.4,1), width .35s cubic-bezier(.34,1.1,.4,1), opacity .2s", pointerEvents: "none", zIndex: 0 },
  body: { display: "flex" },
  sidebar: { width: 252, padding: "12px 14px 24px", display: "flex", flexDirection: "column", gap: 3, minHeight: "calc(100vh - 60px)", flexShrink: 0 },
  sidebarMobile: { position: "fixed", top: 0, left: 0, bottom: 0, width: 280, background: C.solid, backdropFilter: "blur(40px) saturate(180%)", WebkitBackdropFilter: "blur(40px) saturate(180%)", borderRight: `1px solid ${C.glassBorder}`, zIndex: 50, transform: "translateX(-100%)", transition: "transform .3s cubic-bezier(.22,.61,.36,1)", minHeight: "100vh", boxShadow: `0 0 60px ${C.shadow}` },
  sidebarMobileOpen: { transform: "translateX(0)" },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", backdropFilter: "blur(4px)", WebkitBackdropFilter: "blur(4px)", zIndex: 40 },
  drawerHead: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 6px 14px", marginBottom: 4, borderBottom: `1px solid ${C.line}` },
  drawerTitle: { fontSize: 14, fontWeight: 700 },
  nav: { display: "flex", alignItems: "center", gap: 13, padding: "11px 15px", borderRadius: 12, color: C.sub, fontSize: 13.5, cursor: "pointer", fontWeight: 500 },
  sidebarLabel: { fontSize: 11, textTransform: "uppercase", letterSpacing: 0.5, color: C.faint, fontWeight: 700, padding: "4px 15px 8px" },
  navActive: { background: C.green, color: C.onAccent, boxShadow: `0 6px 16px ${C.green}3a` },
  main: { flex: 1, padding: "8px 8px 24px", minWidth: 0, width: "100%", maxWidth: 1080, margin: "0 auto" },
  // hero
  hero: { position: "relative", borderRadius: 20, overflow: "hidden", background: C.heroGrad, border: `1px solid ${C.line}`, marginBottom: 22 },
  heroGlow: { display: "none" },
  heroContent: { position: "relative", padding: "24px 28px" },
  heroTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 22 },
  heroLabel: { fontSize: 12, color: C.heroLabel, opacity: 0.95, marginBottom: 6 },
  heroTitle: { fontSize: 26, fontWeight: 800, letterSpacing: -0.6, whiteSpace: "nowrap" },
  weekPickerWrap: { position: "relative", marginTop: 4, display: "inline-block" },
  weekBtn: { display: "inline-flex", alignItems: "center", gap: 10, background: C.panel2, border: `1px solid ${C.glassBorder}`, color: C.text, cursor: "pointer", padding: "10px 16px", borderRadius: 14, fontFamily: "inherit", boxShadow: `inset 0 1px 0 ${C.glassHi}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  // Селектор недели ФП в шапке (общий для всех разделов)
  topWeekWrap: { position: "relative", flexShrink: 0 },
  topWeekBtn: { display: "inline-flex", alignItems: "center", gap: 7, height: 40, color: C.text, cursor: "pointer", padding: "0 14px", borderRadius: 99, fontFamily: "inherit", fontSize: 13, fontWeight: 700, whiteSpace: "nowrap", fontVariantNumeric: "tabular-nums" },
  weekOverlay: { position: "fixed", inset: 0, zIndex: 60 },
  weekMenu: { position: "absolute", top: 50, left: 0, zIndex: 61, width: 260, maxHeight: 320, overflowY: "auto", background: C.solid, backdropFilter: "blur(28px) saturate(180%)", WebkitBackdropFilter: "blur(28px) saturate(180%)", border: `1px solid ${C.glassBorder}`, borderRadius: 16, padding: 8, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 16px 40px ${C.shadow}` },
  weekMenuHead: { fontSize: 11, textTransform: "uppercase", letterSpacing: 0.5, color: C.faint, fontWeight: 700, padding: "6px 10px 10px" },
  weekOption: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, width: "100%", padding: "10px 12px", borderRadius: 8, background: "transparent", border: "none", color: C.text, fontSize: 13.5, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  weekOptionOn: { background: C.panel2 },
  weekTag: { fontSize: 10.5, fontWeight: 700, color: C.green, background: `${C.green}1a`, padding: "2px 8px", borderRadius: 20, marginLeft: "auto" },
  heroStats: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: "18px 28px" },
  statLabel: { fontSize: 12, color: C.heroStat, marginBottom: 6, fontWeight: 500 }, statValue: { fontSize: 24, fontWeight: 700, fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap", letterSpacing: "-0.02em" }, statUnit: { fontSize: 12, color: C.sub, fontWeight: 600 },
  rolePill: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, padding: "8px 13px", borderRadius: 20, background: "rgba(0,0,0,0.3)", border: `1px solid ${C.line}`, cursor: "pointer", userSelect: "none", color: C.text },
  roleDot: { width: 8, height: 8, borderRadius: "50%" },
  // fund card
  cardWrap: { overflowX: "auto", borderRadius: 22, border: `1px solid ${C.glassBorder}`, marginBottom: 18, WebkitOverflowScrolling: "touch", boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 10px 30px ${C.shadow}` },
  // Контейнер данных финэкранов — непрозрачный «банковский» фон для читаемости
  // плотных таблиц. Стекло остаётся для навигации и герой-карточек.
  card: { background: C.panel, borderRadius: 22, border: `1px solid ${C.glassBorder}`, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 10px 30px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  cardHead: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 22px" },
  cardTitle: { fontSize: 17, fontWeight: 800 }, cardTotal: { fontSize: 16, fontWeight: 700, color: C.sub }, unit: { fontSize: 12, color: C.faint },
  subHead: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 22px", background: C.panel2 },
  subHeadTitle: { fontSize: 13, fontWeight: 700, color: C.text }, subHeadAppr: { fontSize: 13, color: C.sub },
  frow: { display: "grid", gridTemplateColumns: "160px 64px minmax(140px,1fr) 165px 165px", alignItems: "start", padding: "14px 22px", minWidth: 720 },
  frowHead: { fontSize: 11, textTransform: "uppercase", letterSpacing: 0.5, color: C.faint, padding: "12px 22px" },
  frowTotal: { background: C.panel2 },
  fName: { display: "flex", flexDirection: "column", gap: 6, paddingRight: 14, lineHeight: "20px" },
  fundTop: { display: "flex", alignItems: "baseline", gap: 9, fontSize: 14, lineHeight: "20px" },
  fundTopM: { display: "flex", flexDirection: "column", gap: 1, fontSize: 12.5, lineHeight: 1.2 },
  fundNameM: { fontSize: 12.5, lineHeight: 1.2 },
  fundCode: { fontSize: 11, color: C.green, fontWeight: 700 },
  fPct: { fontSize: 13, color: C.sub, textAlign: "left", fontVariantNumeric: "tabular-nums", paddingLeft: 4, alignSelf: "start", lineHeight: "20px", display: "flex", alignItems: "center", gap: 2 },
  pctInput: { width: 44, background: C.inputBg, border: `1px solid ${C.line}`, borderRadius: 8, padding: "4px 6px", color: C.text, fontSize: 13, fontFamily: "inherit", textAlign: "right", outline: "none", fontVariantNumeric: "tabular-nums", MozAppearance: "textfield" },
  pctSign: { fontSize: 12, color: C.sub }, fNum: { textAlign: "right", fontVariantNumeric: "tabular-nums", fontSize: 14, whiteSpace: "nowrap", alignSelf: "start", lineHeight: "20px" },
  bar: { height: 4, background: C.barBg, borderRadius: 3, overflow: "hidden", maxWidth: 300 }, barFill: { height: "100%", background: C.green, borderRadius: 3, transition: "width .5s ease, background .4s ease" },
  actions: { display: "flex", gap: 8, flexWrap: "nowrap", alignItems: "center" },
  // income table
  toolbar: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 14, flexWrap: "wrap" },
  tbLeft: { display: "flex", alignItems: "center", gap: 10 }, tbRight: { display: "flex", alignItems: "center", gap: 10 },
  period: { fontSize: 13, color: C.sub, marginLeft: 6 },
  viewToggle: { display: "flex", background: C.panel, border: `1px solid ${C.line}`, borderRadius: 12, padding: 3, gap: 2 },
  viewBtn: { display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 12px", borderRadius: 8, background: "transparent", border: "none", color: C.sub, fontSize: 12.5, cursor: "pointer", fontFamily: "inherit", fontWeight: 600 },
  viewBtnOn: { background: C.panel2, color: "#fff" },
  tableWrap: { overflowX: "auto", borderRadius: 16, border: `1px solid ${C.line}`, WebkitOverflowScrolling: "touch" },
  table: { background: C.panel, borderRadius: 18, border: `1px solid ${C.glassBorder}`, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 10px 30px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  row: { position: "relative", display: "grid", gridTemplateColumns: "36px 44px 1fr 200px 200px 86px", alignItems: "center", padding: "0 14px", minHeight: 46, minWidth: 760 },
  head: { background: C.panel2, fontSize: 11, textTransform: "uppercase", letterSpacing: 0.5, color: C.sub, minHeight: 44, fontWeight: 700 },
  rowChild: { background: C.rowChild }, totalRow: { background: C.panel2, minHeight: 52 },
  marker: { position: "absolute", left: 0, top: 0, bottom: 0, width: 4 },
  cCheck: { display: "flex", alignItems: "center", justifyContent: "center" }, cId: { fontSize: 13, color: C.sub },
  cName: { display: "flex", alignItems: "center", gap: 8, fontSize: 13.5, overflow: "hidden", whiteSpace: "nowrap" },
  code: { fontSize: 12, color: C.sub, fontWeight: 600, flexShrink: 0 }, expander: { cursor: "pointer", display: "inline-flex", color: C.sub },
  cNum: { textAlign: "right", fontVariantNumeric: "tabular-nums", fontSize: 13.5, paddingRight: 8 },
  cAct: { display: "flex", gap: 5, justifyContent: "flex-end", alignItems: "center" },
  miniBtn: { width: 28, height: 28, borderRadius: 8, background: C.panel2, border: `1px solid ${C.line}`, color: C.sub, cursor: "pointer", display: "grid", placeItems: "center" },
  // buttons
  btnGreen: { display: "inline-flex", alignItems: "center", gap: 7, background: `color-mix(in srgb, ${C.green} 60%, transparent)`, color: "#fff", border: "1px solid rgba(255,255,255,0.30)", padding: "11px 18px", borderRadius: 14, fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap", flexShrink: 0, textShadow: "0 1px 2px rgba(0,70,28,0.45)", boxShadow: `inset 0 1px 0 rgba(255,255,255,0.55), inset 0 -3px 8px ${C.green}55, 0 6px 18px ${C.green}40, 0 2px 6px rgba(0,0,0,0.18)`, backdropFilter: "blur(8px) saturate(160%)", WebkitBackdropFilter: "blur(8px) saturate(160%)" },
  btnGhost: { display: "inline-flex", alignItems: "center", gap: 6, background: "linear-gradient(180deg, rgba(255,255,255,0.22) 0%, rgba(255,255,255,0.08) 100%)", color: C.text, border: "1px solid rgba(255,255,255,0.45)", padding: "11px 16px", borderRadius: 14, fontSize: 13, cursor: "pointer", fontWeight: 600, fontFamily: "inherit", whiteSpace: "nowrap", flexShrink: 0, boxShadow: `inset 0 2px 2px rgba(255,255,255,0.5), inset 0 -2px 6px rgba(0,0,0,0.06), 0 8px 20px ${C.shadow}`, backdropFilter: "blur(16px) saturate(150%)", WebkitBackdropFilter: "blur(16px) saturate(150%)" },
  empty: { padding: "28px 22px", color: C.faint, fontSize: 14, textAlign: "center" },
  mCard: { margin: "10px 12px 0", padding: "14px 16px", background: C.panel2, borderRadius: 16 },
  mTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10, gap: 10 },
  mName: { fontSize: 14, fontWeight: 600 },
  mPct: { fontSize: 13, color: C.sub, fontWeight: 700, flexShrink: 0 },
  mRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "7px 0", borderTop: `1px solid ${C.line}` },
  mLabel: { fontSize: 12.5, color: C.sub },
  mVal: { fontSize: 14, fontVariantNumeric: "tabular-nums", color: C.text },
  mTotal: { margin: "12px 12px 0", padding: "6px 16px 12px", background: C.panel2, borderRadius: 16 },
  mActions: { display: "flex", flexWrap: "wrap", gap: 8, padding: "14px 12px 16px" },

  // ---- Шапка-«герой» с крупным числом (Доходы/Расходы/дашборд) ----
  // Та же градиентная оболочка, что и st.hero — общий визуальный паттерн.
  incHero: { position: "relative", overflow: "hidden", background: C.panel, border: `1px solid ${C.glassBorder}`, borderRadius: 24, padding: "24px 24px", marginBottom: 16, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 10px 30px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  incHeroGlow: { display: "none" },
  incHeroInner: { position: "relative", display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 16, flexWrap: "wrap" },
  incHeroLabel: { fontSize: 12.5, color: C.heroLabel, letterSpacing: 0.3, marginBottom: 10 },
  incHeroValue: { fontSize: 38, fontWeight: 800, letterSpacing: -0.5, lineHeight: 1, fontVariantNumeric: "tabular-nums" },
  incHeroUnit: { fontSize: 16, fontWeight: 600, color: C.heroStat },
  incHeroSub: { display: "flex", alignItems: "center", gap: 8, marginTop: 12, fontSize: 12.5, color: C.heroStat, flexWrap: "wrap" },
  incList: { display: "flex", flexDirection: "column", gap: 12 },
  locCard: { background: C.panel, border: `1px solid ${C.glassBorder}`, borderRadius: 18, overflow: "hidden", boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 8px 24px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  // Непрозрачный вариант карточки для плотных данных (Доходы/Расходы/Счета) —
  // «банковский» фон; locCard (стекло) остаётся для обзорных модулей.
  dataCard: { background: C.panel, border: `1px solid ${C.glassBorder}`, borderRadius: 18, overflow: "hidden", boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 8px 24px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  locHead: { display: "flex", alignItems: "center", gap: 14, padding: "16px 18px", cursor: "pointer", userSelect: "none", transition: "background .15s" },
  locDot: { width: 10, height: 10, borderRadius: 4, flexShrink: 0 },
  locTitle: { flex: 1, minWidth: 0 },
  locName: { fontSize: 15, fontWeight: 700, lineHeight: 1.25 },
  locCode: { fontSize: 12, color: C.faint, marginTop: 3 },
  locRight: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 4, flexShrink: 0 },
  locSum: { fontSize: 16, fontWeight: 700, fontVariantNumeric: "tabular-nums" },
  locUnit: { fontSize: 11.5, fontWeight: 600, color: C.sub },
  locChevron: { color: C.faint, display: "flex", transition: "transform .2s", flexShrink: 0 },
  locBody: { borderTop: `1px solid ${C.line}`, padding: "6px 0" },
  itemRow: { display: "grid", gridTemplateColumns: "1fr 120px 120px", alignItems: "center", gap: 12, padding: "10px 18px 10px 24px", transition: "background .15s" },
  itemHeadRow: { display: "grid", gridTemplateColumns: "1fr 120px 120px", alignItems: "center", gap: 12, padding: "8px 18px 8px 24px" },
  itemHeadCell: { fontSize: 10.5, fontWeight: 700, letterSpacing: 0.5, textTransform: "uppercase", color: C.faint, textAlign: "right" },
  itemDot: { display: "none" },
  itemName: { display: "flex", alignItems: "baseline", gap: 9, fontSize: 13.5, minWidth: 0 },
  itemCode: { fontSize: 11, color: C.green, fontWeight: 700, flexShrink: 0 },
  itemPrev: { fontSize: 13, color: C.sub, fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap", textAlign: "right" },
  itemCur: { fontSize: 14, fontWeight: 600, fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap", textAlign: "right" },
  trend: { display: "inline-flex", alignItems: "center", gap: 2, fontWeight: 700, fontVariantNumeric: "tabular-nums" },

  // ---- Модальная форма ----
  mdOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.55)", zIndex: 70, display: "flex", alignItems: "center", justifyContent: "center", padding: 16 },
  mdCard: { width: "min(560px, 100%)", maxHeight: "92vh", overflowY: "auto", background: C.panel, border: `1px solid ${C.glassBorder}`, borderRadius: 20, padding: "20px 22px 18px", boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 24px 60px ${C.shadow}`, backdropFilter: "blur(24px) saturate(160%)", WebkitBackdropFilter: "blur(24px) saturate(160%)" },
  mdHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, gap: 10 },
  mdTitle: { fontSize: 17, fontWeight: 800 },
  mdGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  mdFull: { gridColumn: "1 / -1" },
  mdInput: { width: "100%", background: C.inputBg, border: `1px solid ${C.line}`, borderRadius: 8, padding: "9px 11px", color: C.text, fontSize: 13.5, fontFamily: "inherit", outline: "none" },
  mdSelect: { width: "100%", background: C.panel2, color: C.text, border: `1px solid ${C.line}`, borderRadius: 8, padding: "9px 11px", fontSize: 13, fontFamily: "inherit", cursor: "pointer", outline: "none" },
  mdCheck: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, color: C.sub, cursor: "pointer", userSelect: "none", paddingTop: 4 },
  mdActions: { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 18 },

  // ---- Заявки ----
  reqTabs: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 18 },
  reqTab: { display: "inline-flex", alignItems: "center", gap: 7, background: C.panel, color: C.sub, border: `1px solid ${C.line}`, padding: "9px 14px", borderRadius: 12, fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  reqTabOn: { background: C.green, color: C.onAccent, borderColor: C.green },
  reqTabN: { fontSize: 11, fontWeight: 700, opacity: 0.7 },
  reqList: { display: "flex", flexDirection: "column", gap: 16 },
  reqGroup: { display: "flex", flexDirection: "column", gap: 10 },
  reqGroupHead: { display: "flex", alignItems: "center", gap: 11, padding: "10px 14px", background: C.panel2, borderRadius: 12 },
  reqGroupName: { flex: 1, fontSize: 13.5, fontWeight: 600, minWidth: 0 },
  reqGroupSum: { fontSize: 14, fontWeight: 700, fontVariantNumeric: "tabular-nums", flexShrink: 0 },
  reqCard: { background: C.panel, border: `1px solid ${C.line}`, borderRadius: 16, padding: 16 },
  reqRow: { padding: "16px", margin: "10px 12px", background: C.panel2, border: `1px solid ${C.line}`, borderRadius: 14, boxShadow: `inset 0 1px 0 ${C.glassHi}` },
  reqMain: { display: "flex", alignItems: "flex-start", gap: 14 },
  reqAvatar: { width: 46, height: 46, borderRadius: "50%", display: "grid", placeItems: "center", color: "#fff", fontWeight: 700, fontSize: 15, flexShrink: 0, boxShadow: "inset 0 1px 0 rgba(255,255,255,0.25)" },
  reqInfo: { flex: 1, minWidth: 0 },
  reqTitle: { fontSize: 14, fontWeight: 600, marginBottom: 4 },
  reqMeta: { fontSize: 12, color: C.faint, fontStyle: "italic", lineHeight: 1.5 },
  reqAmountBox: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 6, flexShrink: 0 },
  reqAmount: { fontSize: 17, fontWeight: 700, fontVariantNumeric: "tabular-nums" },
  reqAmountEdit: { display: "flex", alignItems: "center", gap: 5 },
  reqAmountInput: { width: 110, background: C.inputBg, border: `1px solid ${C.line}`, borderRadius: 8, padding: "7px 10px", color: C.text, fontSize: 15, fontWeight: 700, fontFamily: "inherit", textAlign: "right", outline: "none", fontVariantNumeric: "tabular-nums", MozAppearance: "textfield" },
  reqAmountCur: { fontSize: 11.5, fontWeight: 600, color: C.sub },
  reqAmountOrig: { fontSize: 11, color: C.faint },
  reqBadge: { fontSize: 10.5, fontWeight: 700, padding: "3px 9px", borderRadius: 20, whiteSpace: "nowrap" },
  reqControls: { display: "flex", alignItems: "flex-end", gap: 10, marginTop: 14, paddingTop: 14, borderTop: `1px solid ${C.line}`, flexWrap: "wrap" },
  reqField: { display: "flex", flexDirection: "column", gap: 5, flex: 1, minWidth: 150 },
  reqFieldLbl: { fontSize: 10.5, color: C.faint, fontWeight: 600, letterSpacing: 0.3, textTransform: "uppercase" },
  reqSelect: { background: C.panel2, color: C.text, border: `1px solid ${C.line}`, borderRadius: 8, padding: "9px 11px", fontSize: 13, fontFamily: "inherit", cursor: "pointer", outline: "none" },
  reqActions: { display: "flex", gap: 7, flexShrink: 0 },
  reqAct: { width: 38, height: 38, borderRadius: 8, display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", border: "1px solid transparent", transition: "all .15s" },
  reqActAppr: { background: `${C.green}14`, color: C.green, borderColor: `${C.green}33` },
  reqActApprOn: { background: C.green, color: C.onAccent },
  reqActRej: { background: `${C.danger}14`, color: C.danger, borderColor: `${C.danger}33` },
  reqActRejOn: { background: C.danger, color: "#fff" },
  reqActBack: { background: C.panel2, color: C.sub, borderColor: C.line },
  reqActPaid: { background: `${C.info}14`, color: C.info, borderColor: `${C.info}33` },
  reqActPaidOn: { background: C.info, color: "#fff" },
  reqSection: { marginTop: 24, paddingTop: 22, borderTop: `1px solid ${C.line}` },
  reqSectionHead: { display: "flex", alignItems: "center", gap: 10, marginBottom: 16, flexWrap: "wrap" },
  reqSectionTitle: { fontSize: 18, fontWeight: 800, margin: 0 },
  reqSectionSub: { fontSize: 12.5, color: C.faint },
  reqBlockedTag: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11.5, fontWeight: 700, color: C.danger, background: `${C.danger}1a`, padding: "4px 10px", borderRadius: 20 },

  // ---- Итог ФП ----
  // Тулбар Директивы (авто-распределение + сравнение с прошлой неделей)
  dirToolbar: { display: "flex", alignItems: "center", gap: 10, marginBottom: 16, flexWrap: "wrap" },
  dirToggleOn: { background: C.green, color: C.onAccent, borderColor: "transparent" },
  mSelectAll: { display: "flex", alignItems: "center", gap: 9, padding: "12px 16px 2px" },
  fpCard: { background: C.panel, border: `1px solid ${C.glassBorder}`, borderRadius: 20, padding: "20px 22px", marginTop: 18, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 8px 24px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  fpRows: { display: "flex", flexDirection: "column" },
  fpRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 0", gap: 16 },
  fpLabel: { fontSize: 13.5, color: C.sub },
  fpLabelBold: { fontSize: 14.5, fontWeight: 700 },
  fpVal: { fontSize: 14, fontVariantNumeric: "tabular-nums", color: C.text },
  fpValBold: { fontSize: 16, fontWeight: 800, fontVariantNumeric: "tabular-nums" },
  fpRemainder: { borderTop: `1px solid ${C.line}`, marginTop: 4, paddingTop: 14 },
  fpActions: { display: "flex", alignItems: "center", justifyContent: "center", gap: 10, marginTop: 18, paddingTop: 18, borderTop: `1px solid ${C.line}`, flexWrap: "wrap" },
  fpBtn: { display: "inline-flex", alignItems: "center", gap: 8, padding: "11px 16px", borderRadius: 12, fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", border: "1px solid transparent" },
  fpBtnGhost: { background: C.panel2, color: C.text, borderColor: C.line },
  fpBtnDanger: { background: `${C.danger}1a`, color: C.danger, borderColor: `${C.danger}44` },
  fpBtnPrimary: { background: C.green, color: C.onAccent },
  fpBtnClosed: { background: C.panel2, color: C.sub, borderColor: C.line },
  fpLink: { display: "inline-flex", alignItems: "center", gap: 7, background: "transparent", border: "none", color: C.blueLink, fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", marginLeft: "auto" },
  reqCommentWrap: { display: "flex", flexDirection: "column", gap: 5, marginTop: 12 },
  reqError: { display: "flex", alignItems: "center", gap: 7, marginTop: 10, padding: "9px 12px", background: `${C.danger}1a`, color: C.danger, border: `1px solid ${C.danger}44`, borderRadius: 8, fontSize: 12.5, fontWeight: 600 },
  // Парный к reqError баннер успеха (единый стиль вместо инлайн-переопределения
  // reqError зелёным в каждом экране). C.green — тема-зависимый, контраст в light ок.
  reqSuccess: { display: "flex", alignItems: "center", gap: 7, marginTop: 10, padding: "9px 12px", background: `${C.green}1a`, color: C.green, border: `1px solid ${C.green}44`, borderRadius: 8, fontSize: 12.5, fontWeight: 600 },
  reqTotalBar: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14, marginTop: 16, padding: "16px 20px", background: C.panel2, border: `1px solid ${C.line}`, borderRadius: 16, flexWrap: "wrap" },
  reqTotalLabel: { fontSize: 14, fontWeight: 700 },
  reqTotalRight: { display: "flex", alignItems: "center", gap: 18, flexWrap: "wrap" },
  reqTotalApproved: { fontSize: 13, color: C.sub },
  reqTotalSum: { fontSize: 18, fontWeight: 800, fontVariantNumeric: "tabular-nums" },
  reqComment: { background: C.panel2, color: C.text, border: `1px solid ${C.line}`, borderRadius: 8, padding: "9px 11px", fontSize: 13, fontFamily: "inherit", resize: "vertical", outline: "none", lineHeight: 1.5 },
  numInput: { width: 180, textAlign: "right", background: C.inputBg, border: `1px solid ${C.line}`, borderRadius: 8, padding: "8px 12px", color: C.text, fontSize: 14, fontFamily: "inherit", outline: "none", fontVariantNumeric: "tabular-nums" },
  vibeNote: { marginTop: 18, padding: "16px 18px", background: C.panel2, border: `1px solid ${C.line}`, borderRadius: 16, fontSize: 13, color: C.sub, lineHeight: 1.6 },
  stub: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 12, padding: "100px 20px", color: C.sub },
  stubTitle: { fontSize: 20, fontWeight: 700, color: C.text }, stubText: { fontSize: 13, color: C.faint },

  // ---- Ресторан ----
  rSectionHead: { display: "flex", alignItems: "center", gap: 10, marginBottom: 18, flexWrap: "wrap" },
  zoneTitle: { fontSize: 12, textTransform: "uppercase", letterSpacing: 0.5, color: C.faint, fontWeight: 700, marginBottom: 10 },
  // заказы
  ordGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 14 },
  ordCard: { background: C.panel, border: `1px solid ${C.glassBorder}`, borderRadius: 18, padding: 16, display: "flex", flexDirection: "column", gap: 12, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 8px 24px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  ordTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 10 },
  ordTable: { fontSize: 16, fontWeight: 800 },
  ordMeta: { fontSize: 11.5, color: C.faint, marginTop: 3 },
  ordBadge: { fontSize: 11, fontWeight: 700, padding: "4px 10px", borderRadius: 20, whiteSpace: "nowrap" },
  ordItems: { display: "flex", flexDirection: "column", gap: 6, padding: "10px 0", borderTop: `1px solid ${C.line}`, borderBottom: `1px solid ${C.line}` },
  ordItem: { display: "flex", justifyContent: "space-between", fontSize: 13.5 },
  ordQty: { color: C.sub, fontWeight: 700 },
  ordFoot: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 },
  ordSum: { fontSize: 16, fontWeight: 800, fontVariantNumeric: "tabular-nums" },
  // столы
  tableGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))", gap: 12 },
  tableCard: { background: C.panel, border: "1.5px solid", borderRadius: 16, padding: 14, boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 6px 18px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  tableTop: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  tableName: { fontSize: 15, fontWeight: 700 },
  tableDot: { width: 9, height: 9, borderRadius: "50%", flexShrink: 0 },
  tableSeats: { fontSize: 12, color: C.faint, marginTop: 4 },
  tableStatus: { fontSize: 12.5, fontWeight: 700, marginTop: 8 },
  tableInfo: { fontSize: 11.5, color: C.sub, marginTop: 6, lineHeight: 1.4 },
  // меню
  menuRow: { display: "flex", alignItems: "center", gap: 13, padding: "11px 18px", borderBottom: `1px solid ${C.line}` },
  menuPhoto: { width: 46, height: 46, borderRadius: 12, background: C.panel2, display: "grid", placeItems: "center", overflow: "hidden", flexShrink: 0 },
  menuImg: { width: "100%", height: "100%", objectFit: "cover" },
  menuInfo: { flex: 1, minWidth: 0 },
  menuName: { fontSize: 14, fontWeight: 600 },
  menuCost: { fontSize: 11.5, color: C.faint, marginTop: 2 },
  menuPrice: { fontSize: 15, fontWeight: 700, fontVariantNumeric: "tabular-nums", flexShrink: 0 },
  // склад
  stockAlert: { display: "flex", alignItems: "center", gap: 9, padding: "12px 16px", background: `${C.danger}1a`, color: C.danger, border: `1px solid ${C.danger}44`, borderRadius: 12, fontSize: 13, fontWeight: 600, marginBottom: 16 },
  stockList: { background: C.panel, border: `1px solid ${C.glassBorder}`, borderRadius: 18, overflow: "hidden", boxShadow: `inset 0 1px 0 ${C.glassHi}, 0 8px 24px ${C.shadow}`, backdropFilter: "blur(20px) saturate(160%)", WebkitBackdropFilter: "blur(20px) saturate(160%)" },
  stockRow: { display: "grid", gridTemplateColumns: "1fr 110px 100px 110px", gap: 10, padding: "13px 18px", alignItems: "center", borderBottom: `1px solid ${C.line}`, fontSize: 13.5 },
  stockHead: { background: C.panel2, fontSize: 11, textTransform: "uppercase", letterSpacing: 0.4, color: C.faint, fontWeight: 700 },
  stockName: { fontWeight: 600, display: "flex", alignItems: "center" },
});
