export enum Tables {
  categories = 'category',
  closings = 'day_closing',
  customers = 'customer',
  discounts = 'discount',
  discount_reasons = 'discount_reason',
  role_discount_policies = 'role_discount_policy',
  order_discounts = 'order_discount',
  coupons = 'coupon',
  coupon_redemptions = 'coupon_redemption',
  floors = 'floor',
  tables = 'floor_table',
  kitchens = 'kitchen',
  workflows = 'workflow',
  workflow_stages = 'workflow_stage',
  dishes = 'menu_item',
  dishes_recipes = 'menu_item_recipe',
  modifier_groups = 'modifier_group',
  modifiers = 'modifier',
  dish_modifier_groups = 'menu_item_modifier_group',
  menus = 'menu',
  menu_menu_items = 'menu_menu_item',

  orders = 'order',
  order_extras = 'order_extras',
  order_items = 'order_item',
  order_items_kitchen = 'order_item_kitchen',
  order_meta = 'order_meta',
  order_coupons = 'order_coupon',
  order_payment = 'order_payment',
  order_merge = 'order_merge',
  order_split = 'order_split',
  order_voids = 'order_void',
  order_refunds = 'order_refund',

  order_types = 'order_type',
  extras = 'extra',
  payment_types = 'payment_type',
  payment_type_gateway_configs = 'payment_type_gateway_config',
  payment_webhooks = 'payment_webhook',
  printers = 'printer',
  taxes = 'tax',
  users = 'user',
  user_roles = 'user_role',
  shifts = 'shift',
  time_entries = 'time_entry',
  tip_distributions = 'tip_distribution',
  tip_distribution_user_shares = 'tip_distribution_user_share',

  documents = 'document',

  inventory_items = 'inventory_item',
  inventory_suppliers = 'inventory_supplier',
  inventory_categories = 'inventory_category',
  inventory_stores = 'inventory_store',
  inventory_purchase_orders = 'inventory_purchase_order',
  inventory_purchase_order_items = 'inventory_purchase_order_item',
  inventory_purchases = 'inventory_purchase',
  inventory_purchase_items = 'inventory_purchase_item',
  inventory_purchase_returns = 'inventory_purchase_return',
  inventory_purchase_return_items = 'inventory_purchase_return_item',
  inventory_issues = 'inventory_issue',
  inventory_issue_items = 'inventory_issue_item',
  inventory_issue_returns = 'inventory_issue_return',
  inventory_issue_return_items = 'inventory_issue_return_item',
  inventory_item_groups = 'inventory_item_group',
  inventory_item_group_items = 'inventory_item_group_item',
  inventory_wastes = 'inventory_item_waste',
  inventory_waste_items = 'inventory_item_waste_item',

  kitchen_reconciliations = 'kitchen_reconciliation',
  kitchen_reconciliation_items = 'kitchen_reconciliation_item',
  kitchen_stock_counts = 'kitchen_stock_count',
  kitchen_wastes = 'kitchen_waste',
  kitchen_staff_meals = 'kitchen_staff_meal',
  kitchen_complimentary_items = 'kitchen_complimentary_item',
  kitchen_reconciliation_revisions = 'kitchen_reconciliation_revision',
  stock_transfers = 'stock_transfer',
  stock_transfer_items = 'stock_transfer_item',

  recipes = 'recipe',
  recipe_items = 'recipe_item',
  recipe_outputs = 'recipe_output',
  production_batches = 'production_batch',
  production_batch_inputs = 'production_batch_input',
  production_batch_outputs = 'production_batch_output',

  buffet_menus = 'buffet_menu',
  buffet_menu_items = 'buffet_menu_item',
  buffet_sessions = 'buffet_session',
  buffet_production_batches = 'buffet_production_batch',
  buffet_stock_snapshots = 'buffet_stock_snapshot',
  buffet_guest_counts = 'buffet_guest_count',
  buffet_waste_logs = 'buffet_waste_log',
  buffet_consumption_logs = 'buffet_consumption_log',

  settings = 'setting',

  auth_permission = 'auth_permission',
  tracking = 'tracking',

  accounts = 'account',
  account_groups = 'account_group',
  account_journal_entries = 'account_journal_entry',
  account_journal_lines = 'account_journal_line'
}
